version: '2'

networks:
  app-tier:
    driver: bridge
    external: true

services:
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka-server
    container_name: kafka-server
    ports:
      - '9092:9092'
      - '9094:9094'
    networks:
      - app-tier
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=1024
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-server:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  db:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: kaspoadmin
      POSTGRES_PASSWORD: kaspo
      POSTGRES_DB: kaspodb

    volumes:
      - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql

    ports:
      - '5432:5432'

    networks:
      - app-tier
